name: Android CI

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1.4.3
      - name: Setup Angular
        run: npm install -g @angular/cli
      - name: Setup Ionic
        run: npm install -g @ionic/cli
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: NPM Install
        run: npm install
      - name: Fetch Data
        run: node fetchLaunches.ts
      - name: Build with Ionic
        run: ionic build --prod
      - name: Capacitor Update
        run: npx cap update android
      - name: Capacitor Copy
        run: npx cap copy
      - name: Build Number
        run: echo $GITHUB_RUN_ID
      - name: Build with Gradle
        run: cd android && ./gradlew bundleRelease
      - name: Sign Bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Safe Signed Release Bundle Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app-bundle-signed
          path: android/app/build/outputs/bundle/release/app-release.aab
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1.0.4
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: de.th105.launchschedule
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
