name: Android CI

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1.4.3
      - name: Setup Angular
        run: npm install -g @angular/cli
      - name: Setup Ionic
        run: npm install -g @ionic/cli
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: NPM Install
        run: npm install
      - name: Fetch Data
        run: node fetchLaunches.ts
      - name: Build with Ionic
        run: ionic build --prod
      - name: Capacitor Update
        run: npx cap update android
      - name: Capacitor Copy
        run: npx cap copy
      - name: Make gradlew executable
        run: chmod +x ./android/gradlew
      - name: Build with Gradle
        run: cd android && ./gradlew bundleRelease
      - name: Upload Release Bundle
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app-bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
